Packet counting 모듈 제작
kaist-cp/corundum-old pull request #1
Opened 2020-10-09 08:06 UTC by lkaybob

* 눈여겨보실 파일은 `fpga/mqnic/VCU1525/fpga_100g/rtl/ids/packet_monitor.v` 입니다.
  * `fpga/mqnic/VCU1525/fpga_100g/rtl/ids/packet_monitor.v`는 `fpga/common/rtl/port.v`에서 instantiate됩니다.
  * 그 외의 수정사항들은 디버깅을 위해 디버그 코어를 추가한 것 or Makefile로 작업하기 위해 만든 수정사항들입니다.
* Packet counting 로직은 기본적으로 corundum의 `dma_client_axis_sink.v`의 것을 가져왔습니다.
  * `dma_client_axis_sink.v`를 이해하고, 패킷 수를 셀 수 있을 정도로 아주 간소화해서 구현했습니다.
* counting된 패킷수는 현재 Vivado의 hardware manager에서 ILA core로 확인이 가능합니다.

IDS 로직도 같이 올리려고 했는데, host machine에서 패킷이 인식이 안 되는 심각한 오류가 발견되서 일단 이번 PR에서는 제외했습니다...

2020-10-09 13:37 UTC, jeehoonkang requested changes
- 제가 로직을 자세히 리뷰드릴 수 있을 수준이 못되는 것 같습니다 ㅜ  걍 SW engineer로서 눈에 보이는 것만 리뷰 드렸습니다.

- 앞으로 해야할 일을 로드맵으로 정리해서 issue로 남겨주세요.

2020-10-09 13:37 UTC, jeehoonkang commented on fpga/common/rtl/port.v
> +//ila_axis_desc port_rx_axis_desc_inst(
주석처리된건 무엇인지 궁금합니다.  필요하면 설명을 주석으로 남기는게 좋겠습니다.

2020-10-09 13:37 UTC, jeehoonkang commented on fpga/lib/pcie/rtl/dma_client_axis_sink.v
> +//ila_ram ila_monitor_inst (
위와 마찬가지입니다.  모든 주석처리된 추가된 코드엔 설명 남겨주시길 부탁드려요-

2020-10-09 13:37 UTC, jeehoonkang commented on fpga/mqnic/VCU1525/fpga_100g/common/vivado.mk
> +	echo "launch_runs synth_1 -jobs 64" >> run_synth.tcl
"64": magic인 것으로 보이는데 혹시 어딘가에서 설정 가능한가요?  아니면 CPU 개수만큼 쓴다거나..

2020-10-09 13:37 UTC, jeehoonkang commented on fpga/mqnic/VCU1525/fpga_100g/common/vivado.mk
> +
additional newline here?

2020-10-09 13:37 UTC, jeehoonkang commented on fpga/mqnic/VCU1525/fpga_100g/ip/ila.tcl
> +] [get_ips ila_packet]
needs a newline

2020-10-09 13:37 UTC, jeehoonkang commented on fpga/mqnic/VCU1525/fpga_100g/fpga.xdc
> +create_clock -period 10 -name pcie_mgt_refclk_1 [get_ports pcie_refclk_p]
needs a newline

2020-10-12 00:14 UTC, lkaybob commented on fpga/common/rtl/port.v
> +//ila_axis_desc port_rx_axis_desc_inst(
패킷 데이터의 datapath를 파악하기 위해 사용했던 debug IP인데, 나중에 다시 사용할 경우가 생길 것 같아 주석처리만 해뒀습니다.

말씀해주신 것처럼 주석으로 위 내용 남겨놓겠습니다.

2020-10-12 00:15 UTC, lkaybob commented on fpga/lib/pcie/rtl/dma_client_axis_sink.v
> +//ila_ram ila_monitor_inst (
https://github.com/kaist-cp/corundum/pull/1#discussion_r502986046 와 동일하게 처리하겠습니다.

2020-10-12 00:18 UTC, lkaybob commented on fpga/mqnic/VCU1525/fpga_100g/common/vivado.mk
> +	echo "launch_runs synth_1 -jobs 64" >> run_synth.tcl
파일 안에 environment variable을 만들어서 따로 빼겠습니다.

2020-10-13 02:15 UTC, lkaybob commented
Hard fork한 repo에서 반영 완료하여 이 PR은 닫겠습니다.

2020-10-13 02:15 UTC, closed without merging